/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    '../../packages/ui/src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
        colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        popover: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--theme-primary, #5B5BF0)',

        // Stitch Design System Colors
        'surface-container': '#ececff',
        'outline-variant': '#c7c4d7',
        'on-secondary': '#ffffff',
        'primary-container': '#5b5bf0',
        'on-primary-fixed-variant': '#2e29c6',
        'error-container': '#ffdad6',
        'on-surface': '#161a30',
        'on-primary-fixed': '#09006b',
        'primary-fixed': '#e1dfff',
        'surface-tint': '#4948de',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        'secondary-container': '#fc695c',
        'on-background': '#161a30',
        'inverse-primary': '#c1c1ff',
        'tertiary-container': '#007e69',
        primary: '#413fd6',
        'on-primary-container': '#f6f2ff',
        'on-tertiary-fixed': '#002019',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#690005',
        'primary-fixed-dim': '#c1c1ff',
        'on-surface-variant': '#464555',
        'on-secondary-fixed-variant': '#8c1715',
        tertiary: '#006352',
        'on-tertiary-container': '#caffee',
        'inverse-on-surface': '#f0efff',
        'tertiary-fixed-dim': '#50dcbd',
        'on-secondary-fixed': '#410002',
        'surface-bright': '#fbf8ff',
        outline: '#767586',
        'on-primary': '#ffffff',
        'surface-variant': '#dee1ff',
        'tertiary-fixed': '#71f9d9',
        surface: '#fbf8ff',
        secondary: '#ae3029',
        'surface-container-high': '#e5e6ff',
        'surface-container-low': '#f4f2ff',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#2b2f46',
        'secondary-fixed': '#ffdad6',
        'surface-dim': '#d5d8f6',
        'secondary-fixed-dim': '#ffb4ab',
        'on-tertiary-fixed-variant': '#005142',
        'surface-container-highest': '#dee1ff',
      },
      borderRadius: {
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '2rem',
        '3xl': '2.5rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['"Nunito Sans"', 'system-ui', '-apple-system', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
