import { useTranslation } from 'react-i18next';
import { VoiceDockLabels, InGameChatDrawerLabels } from '@idavoll/ui';

export function useVoiceLabels() {
  const { t } = useTranslation();

  const voiceDockLabels: VoiceDockLabels = {
    statusConnected: t('voice.connected', '已连麦'),
    statusConnecting: t('voice.connecting', '连接中...'),
    statusError: t('voice.error', '语音异常 (重试)'),
    statusErrorAria: t('voice.errorRetryAria', '语音异常，点击重试开麦'),
    statusOff: t('voice.off', '语音未开启'),
    channelTitle: t('voice.channel', '语音频道'),
    modeHold: t('voice.modeHold', '按住说话'),
    modeHoldAria: t('voice.modeHoldAria', '切换到按住说话模式'),
    modeOpen: t('voice.modeOpen', '自由麦'),
    modeOpenAria: t('voice.modeOpenAria', '切换到自由麦模式'),
    holdToTalk: t('voice.holdToTalk', '按住说话'),
    releaseToMute: t('voice.releaseToMute', '松开发言'),
    holdToTalkAria: t('voice.holdToTalkAria', '按住说话'),
    releaseToMuteAria: t('voice.releaseToMuteAria', '松开静音'),
    mute: t('voice.mute', '静音'),
    unmute: t('voice.unmute', '开麦'),
    muteAria: t('voice.muteAria', '点击静音'),
    unmuteAria: t('voice.unmuteAria', '点击开麦'),
    deafen: t('voice.deafen', '闭音'),
    undeafen: t('voice.undeafen', '取消闭音'),
    deafenAria: t('voice.deafenAria', '闭音'),
    undeafenAria: t('voice.undeafenAria', '取消闭音'),
    playerMuted: t('voice.playerMuted', '(静音)'),
  };

  const chatDrawerLabels: InGameChatDrawerLabels = {
    roomChatTitle: t('voice.roomChatTitle', '房间交流'),
    artistLabel: t('voice.artistPrefix', '画手:'),
    closeDrawerAria: t('voice.closeChatDrawer', '关闭聊天抽屉'),
    chatTab: t('voice.chatTab', '聊天动态'),
    phrasesTab: t('voice.phrasesTab', '快捷短语'),
    holdReadyMuted: t('voice.holdReadyMuted', '按住说话已就绪 (静音中)'),
    micMuted: t('voice.micMutedStatus', '麦克风已静音'),
    micOpenSpeaking: t('voice.micOpenStatus', '麦克风已开 (发言中)'),
    connecting: t('voice.connecting', '正在连接语音...'),
    errorFallback: t('voice.voiceErrorFallback', '语音连接失败'),
    off: t('voice.off', '语音未开启'),
    deafenedBadge: t('voice.deafenedBadge', '(已闭音)'),
    retryUnmute: t('voice.retryUnmute', '重试开麦'),
    retryUnmuteAria: t('voice.errorRetryAria', '重试语音连接'),
    joinVoice: t('voice.joinVoice', '开麦加入'),
    joinVoiceAria: t('voice.joinVoiceAria', '点击开麦加入语音'),
    toggleMicAria: t('voice.unmuteAria', '点击开麦'),
    me: t('voice.me', '(我)'),
    speaking: t('voice.speaking', '发言中'),
    ready: t('voice.ready', '就绪'),
    muted: t('voice.mute', '静音'),
    emptyMessages: t('voice.emptyMessages', '暂无消息记录，开始发言吧！'),
    quickChatPrefix: t('voice.quickChat', '快聊:'),
    holdToTalk: t('voice.holdToTalk', '按住说话'),
    releaseToMute: t('voice.releaseToMute', '松开发言'),
    holdToTalkAria: t('voice.holdToTalkAria', '按住说话'),
    releaseToMuteAria: t('voice.releaseToMuteAria', '松开静音'),
    mute: t('voice.mute', '静音'),
    unmute: t('voice.unmute', '开麦'),
    muteAria: t('voice.muteAria', '点击静音'),
    unmuteAria: t('voice.unmuteAria', '点击开麦'),
    inputPlaceholderArtist: t('voice.inputPlaceholderArtist', '发送聊天消息... (画手禁发答案)'),
    inputPlaceholderGuesser: t('voice.inputPlaceholderGuesser', '发送消息或猜词...'),
    inputAriaArtist: t('voice.inputAriaArtist', '发送聊天消息'),
    inputAriaGuesser: t('voice.inputAriaGuesser', '发送消息或猜词'),
    insertEmojiAria: t('voice.insertEmojiAria', '插入表情符号'),
    send: t('voice.send', '发送'),
    sendAria: t('voice.sendAria', '发送消息'),
    voiceModeLabel: t('voice.voiceModeLabel', '语音模式:'),
    modeHold: t('voice.modeHold', '按住说话'),
    modeHoldAria: t('voice.modeHoldAria', '切换到按住说话模式'),
    modeOpen: t('voice.modeOpen', '自由麦'),
    modeOpenAria: t('voice.modeOpenAria', '切换到自由麦模式'),
    statusConnected: t('voice.statusConnectedFull', '实时语音已连麦'),
    statusConnecting: t('voice.statusConnectingFull', '语音连接中...'),
    statusError: t('voice.statusErrorRetry', '连接异常 (重试)'),
    statusErrorAria: t('voice.statusErrorRetryAria', '语音连接异常，点击重试开麦'),
    statusOff: t('voice.off', '语音未开启'),
    deafen: t('voice.deafen', '闭音'),
    undeafen: t('voice.undeafen', '取消闭音'),
    deafenAria: t('voice.deafenAria', '闭音'),
    undeafenAria: t('voice.undeafenAria', '取消闭音'),
  };

  return {
    voiceDockLabels,
    chatDrawerLabels,
  };
}
